<?php
/**
* @author Virtuosi Media Inc.
* @license: MIT License
* Description: Generates an admin index.php file for VM Framework
* Requirements: PHP 5.2 or higher
*/
class Tools_Installer_AdminIndexGen {
	
	protected $shortAppName;

	/**
	 * @param string $shortAppName - The name of the application as one word
	 */
	function __construct($shortAppName){
		$this->shortAppName = $shortAppName;
		$this->generate();
	}
	
	protected function generate(){
		$xml = new Vm_Xml();
		$bootstrapName = $this->shortAppName.'_Bootstrap';
					
		$fileContents = <<<EOT
<?php
/**
 * Admin index file generated by VM Framework
 * Loads the boostrap file which loads the autoload function, the config file, and sets the DB connection
 */
ob_start("ob_gzhandler"); 
require_once('../includes/$this->shortAppName/Bootstrap.php');
\$system = new $bootstrapName(TRUE);
\$db = \$system->getDbConnection();

/**
 * Enter your admin application code below this line 
 */

?>
EOT;

		$file = new Vm_File('index.php', 'admin');
		$file->write($fileContents);

		if ($file->exists()){
			$this->tableRow = $xml->tr($xml->td("Admin index file generated for $this->shortAppName.", array('class'=>'pass')));
		} else {
			$this->tableRow = $xml->tr($xml->td("Admin index file could not be generated for $this->shortAppName.", array('class'=>'fail')));
		}		
	}

	/**
	 * @return string - The file generation status as an HTML table row
	 */
	public function getTableRow(){
		return $this->tableRow;
	}
}
?>