<?php
/**
* @author Virtuosi Media Inc.
* @license: MIT License
* Description: Generates an autoload function file for VM Framework
* Requirements: PHP 5.2 or higher
*/
class Tools_Installer_AutoloadGen {
	
	protected $shortAppName;

	/**
	 * @param string $shortAppName - The name of the application as one word
	 */
	function __construct($shortAppName){
		$this->shortAppName = $shortAppName;
		$this->generate();
	}
	
	protected function generate(){
		$definedAppName = strtoupper($this->shortAppName);
		$definedAppAdminName = $definedAppName.'_ADMIN';
		$xml = new Vm_Xml();
		
		$fileContents = <<<EOT
<?php
/**
 * Autoloader function generated by VM Framework
 * Classes will only be loaded if the app constant is defined. Use the first app constant for the public index file, the second for the admin index file
 * @param string \$className - The name of the class to automatically load
 */
function __autoload(\$className) {
	\$uris = explode('_', \$className);
	foreach(\$uris as \$key=>\$uri){
		\$uris[\$key] = ucfirst(\$uri);
	}
	
	\$className = implode('/', \$uris);
	if (defined('$definedAppName')){
		require_once('includes/'.\$className.'.php');
	} else if (defined('$definedAppAdminName')) {
		require_once('../includes/'.\$className.'.php');
	}
}
?>
EOT;

		$file = new Vm_File('Autoload.php', 'includes/'.$this->shortAppName);
		$file->write($fileContents);

		if ($file->exists()){
			$this->tableRow = $xml->tr($xml->td("Autoload file generated for $this->shortAppName.", array('class'=>'pass')));
		} else {
			$this->tableRow = $xml->tr($xml->td("Autoload file could not be generated for $this->shortAppName.", array('class'=>'fail')));
		}		
	}

	/**
	 * @return string - The file generation status as an HTML table row
	 */
	public function getTableRow(){
		return $this->tableRow;
	}
}
?>