<?php
/**
* @author Virtuosi Media Inc.
* @license: MIT License
* Description: Generates a MySQL database connection file for VM Framework
* Requirements: PHP 5.2 or higher
*/
class Tools_Installer_ConnectMySqlGen {
	
	protected $shortAppName;

	/**
	 * @param string $shortAppName - The name of the application as one word
	 */
	function __construct($shortAppName){
		$this->shortAppName = $shortAppName;
		$this->generate();
	}
	
	protected function generate(){
		$xml = new Vm_Xml();
		$className = $this->shortAppName.'_Connect';
		
		
		$fileContents = <<<EOT
<?php
/**
 * Database connection class generated by VM Framework
 */
class $className {

	protected \$db;
	
	/**
	 * Creates a database connection
	 * @param string \$dbType - The database type
	 * @param string \$dbName - The database name
	 * @param string \$username - The database username
	 * @param string \$password - The database password
	 * @param string \$host - The host name, usually localhost
	 * @param string \$port - optional - The port on which the database server is running (Postgres, IBM)
	 * @param string \$charset - optional - The client-side character set for the current environment handle (Oracle)
	 */
	function __construct(\$dbType, \$dbName, \$username, \$password, \$host, \$port = NULL, \$charset = NULL){
		try {
			switch(\$dbType) {
				case 'mysql':
					\$this->db = new PDO("mysql:host=\$host;dbname=\$dbName", \$username, \$password);
					break;
			}
		} catch (PDOException \$e) {
			echo "Sorry, a database connection could not be established.";
		    exit;
		}
	}
	
	/**
	 * Gets the database connection
	 * @return object - A PDO database 
	 */
	public function getDbConnection(){
		return \$this->db;
	}
}
?>
EOT;

		$file = new Vm_File('Connect.php', 'includes/'.$this->shortAppName);
		$file->write($fileContents);

		if ($file->exists()){
			$this->tableRow = $xml->tr($xml->td("DB Connection class generated for $this->shortAppName.", array('class'=>'pass')));
		} else {
			$this->tableRow = $xml->tr($xml->td("DB Connection class could not be generated for $this->shortAppName.", array('class'=>'fail')));
		}		
	}

	/**
	 * @return string - The file generation status as an HTML table row
	 */
	public function getTableRow(){
		return $this->tableRow;
	}
}
?>