<?php
/**
* @author Virtuosi Media Inc.
* @license: MIT License
* Description: Generates a version file for VM Framework
* Requirements: PHP 5.2 or higher
*/
class Tools_Installer_VersionGen {
	
	protected $shortAppName;
	protected $fullAppName;
	protected $appDesc;
	protected $developer;

	/**
	 * @param string $shortAppName - The name of the application as one word
	 * @param string $fullAppName - The full name of the application
	 * @param string $appDesc - The description of the application
	 * @param string $developer - The developer name
	 */
	function __construct($shortAppName, $fullAppName, $appDesc, $developer){
		$this->shortAppName = $shortAppName;
		$this->fullAppName = $fullAppName;
		$this->appDesc = $appDesc;
		$this->developer = $developer;
		$this->generate();
	}
	
	protected function generate(){
		$xml = new Vm_Xml();
		$year = date('Y');
				
		$fileContents = <<<EOT
<?php
/**
 * Version class generated by VM Framework
 */
class Version extends Vm_Version {

	/**
	* @param array \$options - optional - Metadata for the package
	*/
	function __construct(\$options = NULL){

		// @var array The default options array for the class
		\$defaultOptions = array(
			'name'=>'$this->fullAppName',
			'copyright'=>'Copyright (c) $year, $this->developer',
			'version'=>'1.0',
			'package'=>'$this->shortAppName',
			'requirements'=>'PHP 5.2.7 or higher and MySQL 5.x',
			'description'=>'$this->appDesc',
			'developer'=>'$this->developer'
		);
		
		parent::__construct();
		\$this->setOptions(\$options, \$defaultOptions);	
	}
}
?>
EOT;

		$file = new Vm_File('Version.php', 'includes');
		$file->write($fileContents);

		if ($file->exists()){
			$this->tableRow = $xml->tr($xml->td("Version file generated for $this->shortAppName.", array('class'=>'pass')));
		} else {
			$this->tableRow = $xml->tr($xml->td("Version file could not be generated for $this->shortAppName.", array('class'=>'fail')));
		}		
	}

	/**
	 * @return string - The file generation status as an HTML table row
	 */
	public function getTableRow(){
		return $this->tableRow;
	}
}
?>